---
title: "Clustering of Local Indicators of Spatial Assocation (LISA) curves"
date: "`r BiocStyle::doc_date()`"
author:
- name: Nicolas Canete
  affiliation:  
  - &WIMR Westmead Institute for Medical Research, University of Sydney, Australia
  email: nicolas.canete@ydney.edu.au
- name: Ellis Patrick
  affiliation:
  - &WIMR Westmead Institute for Medical Research, University of Sydney, Australia
  - School of Mathematics and Statistics, University of Sydney, Australia
  email: ellis.patrick@ydney.edu.au
package: "`r BiocStyle::pkg_ver('spicyR')`"
vignette: >
  %\VignetteIndexEntry{"lisaClust"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output: 
  BiocStyle::html_document
---


```{r message=FALSE}
# load required packages
library(spicyR)
library(tidyverse)

```
 

## Overview

What is LISA clustering?



## Quick start

### Generate toy data

```{r eval=T}
set.seed(51773)
x <- round(c(runif(200),runif(200)+1,runif(200)+2,runif(200)+3,
           runif(200)+3,runif(200)+2,runif(200)+1,runif(200)),4)
y <- round(c(runif(200),runif(200)+1,runif(200)+2,runif(200)+3,
             runif(200),runif(200)+1,runif(200)+2,runif(200)+3),4)

cells <- data.frame(x,y,cellType = factor(paste('c',rep(rep(c(1:2),rep(200,2)),4),sep = '')), imageID = rep(c('s1', 's2'),c(800,800)))

ggplot(cells, aes(x,y, colour = cellType)) + geom_point() + facet_wrap(~imageID)


```

### Create SegmentedCellExperiment object

```{r}

cellExp <- SegmentedCellExperiment(cells, cellTypeString = 'cellType')


```


### Generate LISA curves

```{r}

LCurves <- lisa(cellExp, Rs = c(0.01,0.1, 0.5, 1))

```

### Perform some clustering

```{r}

kM <- kmeans(LCurves,2)
region(cellExp) <- paste('region',kM$cluster,sep = '_')
```


### Plot identified regions

```{r}
hatchingPlot(cellExp)
```


```{r}
hatchingPlot(cellExp, image = c('s1','s2'))
```




### Alternatively, 

```{r}
df <- region(cellExp, image = 's1', annot = TRUE)


p <- ggplot(df, aes(x = x,y = y, colour = cellType)) + 
  geom_point() + 
  geom_hatching(aes(region = region) ,show.legend = TRUE, window = "concave", line.spacing = 21, nbp = 250, window.length = 0) + 
  theme_minimal() + 
  scale_region()

p

```


```{r}

df <- region(cellExp, image = c('s1','s2'), annot = TRUE)

p <- ggplot(df, aes(x = x,y = y, colour = cellType)) + 
  geom_point() + 
  facet_wrap(~imageID) + 
  geom_hatching(aes(region = region),show.legend = TRUE, window = "concave", line.spacing = 21, nbp = 250, window.length = 0) +
  theme_minimal()+ 
  scale_region()
p

```


### We can also control the hatching

```{r}

p <- ggplot(df,aes(x = x,y = y, colour = cellType, region = region)) + 
  geom_point() + 
  facet_wrap(~imageID) +
  geom_hatching(window = "concave", line.spacing = 11, nbp = 1000, line.width = 1.5) +
  theme_minimal()+ 
  scale_region_manual(values = 6:7, labels = c('ab','cd'))

p

```


