---
title: "test"
format: html
editor: visual
---

```{r}
library(SpatialDatasets)
```

```{r}
spe = spe_Keren_2018()
# spe = spe[, spe$imageID %in% c(1, 3, 7, 9)]
spe$tumour_type = droplevels(spe$tumour_type)
```

```{r}
spe$cellType |> unique()
```



```{r}
devtools::load_all("/Users/shreyarao/Desktop/packages/spicyR")
```

```{r eval = F}
spicyTest = spicyR:::spicyGLM(cells = spe,
                              condition = "tumour_type",
                              subject = "DONOR_NO",
                              imageID = "imageID",
                              cellType = "cellType",
                              spatialCoords = c("x", "y"),
                              r = 50,
                              from = spe$cellType |> unique(),
                              to = spe$cellType |> unique(),
                              cores = 1)

```


```{r eval = F}
spicyTest = spicyR:::spicyGLM(cells = spe,
                              condition = "tumour_type",
                              subject = "DONOR_NO",
                              imageID = "imageID",
                              cellType = "cellType",
                              spatialCoords = c("x", "y"),
                              r = 50,
                              from = "CD8_T_cell",
                              to = "Tumour",
                              cores = 1)
spicyTest
```


```{r eval. =F}
s1 = Sys.time()
spicyTest = spicyR:::spicyGLM(cells = spe,
                              condition = "tumour_type",
                              subject = "DONOR_NO",
                              imageID = "imageID",
                              cellType = "cellType",
                              spatialCoords = c("x", "y"),
                              r = 50)
s1 = Sys.time()
s2 - s1
```



```{r}
spe[["cellType"]] |> unique()
```


```{r}
x = "DONOR_NO"
colData(spe) |> dplyr::select(x)
```


