# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dataset_create <- function(x, y, cell_type, image_offsets, n_types) {
    .Call(`_spicyglm_dataset_create`, x, y, cell_type, image_offsets, n_types)
}

dataset_image_areas <- function(ptr, window) {
    .Call(`_spicyglm_dataset_image_areas`, ptr, window)
}

dataset_build_radius_index <- function(ptr, r) {
    invisible(.Call(`_spicyglm_dataset_build_radius_index`, ptr, r))
}

dataset_build_knn <- function(ptr, k, n_threads = 1L) {
    invisible(.Call(`_spicyglm_dataset_build_knn`, ptr, k, n_threads))
}

dataset_poisson_model_data <- function(ptr, image_area, from, to) {
    .Call(`_spicyglm_dataset_poisson_model_data`, ptr, image_area, from, to)
}

dataset_binomial_model_data <- function(ptr, from, to) {
    .Call(`_spicyglm_dataset_binomial_model_data`, ptr, from, to)
}

fit_pair_poisson_cpp <- function(cluster, image, group, n, density, estimator, variance) {
    .Call(`_spicyglm_fit_pair_poisson_cpp`, cluster, image, group, n, density, estimator, variance)
}

fit_pair_binomial_cpp <- function(cluster, image, group, n, k, p0, estimator, variance) {
    .Call(`_spicyglm_fit_pair_binomial_cpp`, cluster, image, group, n, k, p0, estimator, variance)
}

