// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dataset_create
SEXP dataset_create(NumericVector x, NumericVector y, IntegerVector cell_type, IntegerVector image_offsets, int n_types);
RcppExport SEXP _spicyglm_dataset_create(SEXP xSEXP, SEXP ySEXP, SEXP cell_typeSEXP, SEXP image_offsetsSEXP, SEXP n_typesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cell_type(cell_typeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type image_offsets(image_offsetsSEXP);
    Rcpp::traits::input_parameter< int >::type n_types(n_typesSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_create(x, y, cell_type, image_offsets, n_types));
    return rcpp_result_gen;
END_RCPP
}
// dataset_image_areas
NumericVector dataset_image_areas(SEXP ptr, std::string window);
RcppExport SEXP _spicyglm_dataset_image_areas(SEXP ptrSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_image_areas(ptr, window));
    return rcpp_result_gen;
END_RCPP
}
// dataset_build_radius_index
void dataset_build_radius_index(SEXP ptr, double r);
RcppExport SEXP _spicyglm_dataset_build_radius_index(SEXP ptrSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    dataset_build_radius_index(ptr, r);
    return R_NilValue;
END_RCPP
}
// dataset_build_knn
void dataset_build_knn(SEXP ptr, int k, int n_threads);
RcppExport SEXP _spicyglm_dataset_build_knn(SEXP ptrSEXP, SEXP kSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    dataset_build_knn(ptr, k, n_threads);
    return R_NilValue;
END_RCPP
}
// dataset_poisson_model_data
List dataset_poisson_model_data(SEXP ptr, NumericVector image_area, int from, int to);
RcppExport SEXP _spicyglm_dataset_poisson_model_data(SEXP ptrSEXP, SEXP image_areaSEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type image_area(image_areaSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_poisson_model_data(ptr, image_area, from, to));
    return rcpp_result_gen;
END_RCPP
}
// dataset_binomial_model_data
List dataset_binomial_model_data(SEXP ptr, int from, int to);
RcppExport SEXP _spicyglm_dataset_binomial_model_data(SEXP ptrSEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_binomial_model_data(ptr, from, to));
    return rcpp_result_gen;
END_RCPP
}
// fit_pair_poisson_cpp
List fit_pair_poisson_cpp(IntegerVector cluster, IntegerVector image, IntegerVector group, IntegerVector n, NumericVector density, std::string estimator, std::string variance);
RcppExport SEXP _spicyglm_fit_pair_poisson_cpp(SEXP clusterSEXP, SEXP imageSEXP, SEXP groupSEXP, SEXP nSEXP, SEXP densitySEXP, SEXP estimatorSEXP, SEXP varianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type cluster(clusterSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type image(imageSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type density(densitySEXP);
    Rcpp::traits::input_parameter< std::string >::type estimator(estimatorSEXP);
    Rcpp::traits::input_parameter< std::string >::type variance(varianceSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_pair_poisson_cpp(cluster, image, group, n, density, estimator, variance));
    return rcpp_result_gen;
END_RCPP
}
// fit_pair_binomial_cpp
List fit_pair_binomial_cpp(IntegerVector cluster, IntegerVector image, IntegerVector group, IntegerVector n, int k, NumericVector p0, std::string estimator, std::string variance);
RcppExport SEXP _spicyglm_fit_pair_binomial_cpp(SEXP clusterSEXP, SEXP imageSEXP, SEXP groupSEXP, SEXP nSEXP, SEXP kSEXP, SEXP p0SEXP, SEXP estimatorSEXP, SEXP varianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type cluster(clusterSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type image(imageSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< std::string >::type estimator(estimatorSEXP);
    Rcpp::traits::input_parameter< std::string >::type variance(varianceSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_pair_binomial_cpp(cluster, image, group, n, k, p0, estimator, variance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spicyglm_dataset_create", (DL_FUNC) &_spicyglm_dataset_create, 5},
    {"_spicyglm_dataset_image_areas", (DL_FUNC) &_spicyglm_dataset_image_areas, 2},
    {"_spicyglm_dataset_build_radius_index", (DL_FUNC) &_spicyglm_dataset_build_radius_index, 2},
    {"_spicyglm_dataset_build_knn", (DL_FUNC) &_spicyglm_dataset_build_knn, 3},
    {"_spicyglm_dataset_poisson_model_data", (DL_FUNC) &_spicyglm_dataset_poisson_model_data, 4},
    {"_spicyglm_dataset_binomial_model_data", (DL_FUNC) &_spicyglm_dataset_binomial_model_data, 3},
    {"_spicyglm_fit_pair_poisson_cpp", (DL_FUNC) &_spicyglm_fit_pair_poisson_cpp, 7},
    {"_spicyglm_fit_pair_binomial_cpp", (DL_FUNC) &_spicyglm_fit_pair_binomial_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_spicyglm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
