// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// discWindowArea
Rcpp::NumericVector discWindowArea(Rcpp::NumericVector x, Rcpp::NumericVector y, double r, int npoly, Rcpp::List rings);
RcppExport SEXP _spicyR_discWindowArea(SEXP xSEXP, SEXP ySEXP, SEXP rSEXP, SEXP npolySEXP, SEXP ringsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type npoly(npolySEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type rings(ringsSEXP);
    rcpp_result_gen = Rcpp::wrap(discWindowArea(x, y, r, npoly, rings));
    return rcpp_result_gen;
END_RCPP
}
// inhomLCpp
Rcpp::NumericMatrix inhomLCpp(Rcpp::NumericVector x, Rcpp::NumericVector y, Rcpp::IntegerVector type, int nTypes, Rcpp::NumericVector Rs, Rcpp::NumericVector labelVal, Rcpp::LogicalVector isFrom, Rcpp::LogicalVector isTo, Rcpp::NumericVector wt, Rcpp::NumericVector lam, double area, Rcpp::NumericMatrix edge, bool edgeCorrect);
RcppExport SEXP _spicyR_inhomLCpp(SEXP xSEXP, SEXP ySEXP, SEXP typeSEXP, SEXP nTypesSEXP, SEXP RsSEXP, SEXP labelValSEXP, SEXP isFromSEXP, SEXP isToSEXP, SEXP wtSEXP, SEXP lamSEXP, SEXP areaSEXP, SEXP edgeSEXP, SEXP edgeCorrectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type nTypes(nTypesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type labelVal(labelValSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type isFrom(isFromSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type isTo(isToSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type area(areaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< bool >::type edgeCorrect(edgeCorrectSEXP);
    rcpp_result_gen = Rcpp::wrap(inhomLCpp(x, y, type, nTypes, Rs, labelVal, isFrom, isTo, wt, lam, area, edge, edgeCorrect));
    return rcpp_result_gen;
END_RCPP
}
// lmerRandomIntercept
Rcpp::List lmerRandomIntercept(Rcpp::NumericMatrix X, Rcpp::NumericVector y, Rcpp::NumericVector w, Rcpp::IntegerVector group, int G);
RcppExport SEXP _spicyR_lmerRandomIntercept(SEXP XSEXP, SEXP ySEXP, SEXP wSEXP, SEXP groupSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(lmerRandomIntercept(X, y, w, group, G));
    return rcpp_result_gen;
END_RCPP
}
// getPairwiseCpp
Rcpp::NumericMatrix getPairwiseCpp(Rcpp::NumericVector x, Rcpp::NumericVector y, Rcpp::IntegerVector type, Rcpp::IntegerVector offset, int nTypes, Rcpp::NumericVector Rs, bool square, Rcpp::LogicalVector isFrom, Rcpp::LogicalVector isTo, Rcpp::IntegerVector labI, Rcpp::IntegerVector labJ, bool edgeCorrect, bool includeZeroCells, int nThreads);
RcppExport SEXP _spicyR_getPairwiseCpp(SEXP xSEXP, SEXP ySEXP, SEXP typeSEXP, SEXP offsetSEXP, SEXP nTypesSEXP, SEXP RsSEXP, SEXP squareSEXP, SEXP isFromSEXP, SEXP isToSEXP, SEXP labISEXP, SEXP labJSEXP, SEXP edgeCorrectSEXP, SEXP includeZeroCellsSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type nTypes(nTypesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< bool >::type square(squareSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type isFrom(isFromSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type isTo(isToSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type labI(labISEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type labJ(labJSEXP);
    Rcpp::traits::input_parameter< bool >::type edgeCorrect(edgeCorrectSEXP);
    Rcpp::traits::input_parameter< bool >::type includeZeroCells(includeZeroCellsSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(getPairwiseCpp(x, y, type, offset, nTypes, Rs, square, isFrom, isTo, labI, labJ, edgeCorrect, includeZeroCells, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// getPairwisePropCpp
Rcpp::NumericMatrix getPairwisePropCpp(Rcpp::NumericVector x, Rcpp::NumericVector y, Rcpp::IntegerVector type, Rcpp::IntegerVector offset, int nTypes, int k, Rcpp::IntegerVector labI, Rcpp::IntegerVector labJ, bool includeZeroCells, int nThreads);
RcppExport SEXP _spicyR_getPairwisePropCpp(SEXP xSEXP, SEXP ySEXP, SEXP typeSEXP, SEXP offsetSEXP, SEXP nTypesSEXP, SEXP kSEXP, SEXP labISEXP, SEXP labJSEXP, SEXP includeZeroCellsSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type nTypes(nTypesSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type labI(labISEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type labJ(labJSEXP);
    Rcpp::traits::input_parameter< bool >::type includeZeroCells(includeZeroCellsSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(getPairwisePropCpp(x, y, type, offset, nTypes, k, labI, labJ, includeZeroCells, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// scamMonoFit
Rcpp::List scamMonoFit(Rcpp::NumericMatrix XtX, Rcpp::NumericVector Xty, double yty, int n, Rcpp::List S, Rcpp::LogicalVector iv, Rcpp::NumericVector start, Rcpp::IntegerVector blockStart, Rcpp::IntegerVector blockLen);
RcppExport SEXP _spicyR_scamMonoFit(SEXP XtXSEXP, SEXP XtySEXP, SEXP ytySEXP, SEXP nSEXP, SEXP SSEXP, SEXP ivSEXP, SEXP startSEXP, SEXP blockStartSEXP, SEXP blockLenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type XtX(XtXSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Xty(XtySEXP);
    Rcpp::traits::input_parameter< double >::type yty(ytySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type S(SSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type iv(ivSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type blockStart(blockStartSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type blockLen(blockLenSEXP);
    rcpp_result_gen = Rcpp::wrap(scamMonoFit(XtX, Xty, yty, n, S, iv, start, blockStart, blockLen));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spicyR_discWindowArea", (DL_FUNC) &_spicyR_discWindowArea, 5},
    {"_spicyR_inhomLCpp", (DL_FUNC) &_spicyR_inhomLCpp, 13},
    {"_spicyR_lmerRandomIntercept", (DL_FUNC) &_spicyR_lmerRandomIntercept, 5},
    {"_spicyR_getPairwiseCpp", (DL_FUNC) &_spicyR_getPairwiseCpp, 14},
    {"_spicyR_getPairwisePropCpp", (DL_FUNC) &_spicyR_getPairwisePropCpp, 10},
    {"_spicyR_scamMonoFit", (DL_FUNC) &_spicyR_scamMonoFit, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_spicyR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
