// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// discWindowArea
Rcpp::NumericVector discWindowArea(Rcpp::NumericVector x, Rcpp::NumericVector y, double r, int npoly, Rcpp::List rings);
RcppExport SEXP _spicyR_discWindowArea(SEXP xSEXP, SEXP ySEXP, SEXP rSEXP, SEXP npolySEXP, SEXP ringsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type npoly(npolySEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type rings(ringsSEXP);
    rcpp_result_gen = Rcpp::wrap(discWindowArea(x, y, r, npoly, rings));
    return rcpp_result_gen;
END_RCPP
}
// dataset_create
SEXP dataset_create(NumericVector x, NumericVector y, IntegerVector cell_type, IntegerVector image_offsets, int n_types);
RcppExport SEXP _spicyR_dataset_create(SEXP xSEXP, SEXP ySEXP, SEXP cell_typeSEXP, SEXP image_offsetsSEXP, SEXP n_typesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cell_type(cell_typeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type image_offsets(image_offsetsSEXP);
    Rcpp::traits::input_parameter< int >::type n_types(n_typesSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_create(x, y, cell_type, image_offsets, n_types));
    return rcpp_result_gen;
END_RCPP
}
// dataset_image_areas
NumericVector dataset_image_areas(SEXP ptr, std::string window);
RcppExport SEXP _spicyR_dataset_image_areas(SEXP ptrSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_image_areas(ptr, window));
    return rcpp_result_gen;
END_RCPP
}
// dataset_build_radius_index
void dataset_build_radius_index(SEXP ptr, double r);
RcppExport SEXP _spicyR_dataset_build_radius_index(SEXP ptrSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    dataset_build_radius_index(ptr, r);
    return R_NilValue;
END_RCPP
}
// dataset_build_knn
void dataset_build_knn(SEXP ptr, int k, int n_threads);
RcppExport SEXP _spicyR_dataset_build_knn(SEXP ptrSEXP, SEXP kSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    dataset_build_knn(ptr, k, n_threads);
    return R_NilValue;
END_RCPP
}
// dataset_poisson_model_data
List dataset_poisson_model_data(SEXP ptr, NumericVector image_area, int from, int to);
RcppExport SEXP _spicyR_dataset_poisson_model_data(SEXP ptrSEXP, SEXP image_areaSEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type image_area(image_areaSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_poisson_model_data(ptr, image_area, from, to));
    return rcpp_result_gen;
END_RCPP
}
// dataset_build_intensity
void dataset_build_intensity(SEXP ptr, double sigma, double min_lambda, std::string window);
RcppExport SEXP _spicyR_dataset_build_intensity(SEXP ptrSEXP, SEXP sigmaSEXP, SEXP min_lambdaSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type min_lambda(min_lambdaSEXP);
    Rcpp::traits::input_parameter< std::string >::type window(windowSEXP);
    dataset_build_intensity(ptr, sigma, min_lambda, window);
    return R_NilValue;
END_RCPP
}
// dataset_inhom_model_data
List dataset_inhom_model_data(SEXP ptr, NumericVector image_area, int from, int to, bool edge_correct);
RcppExport SEXP _spicyR_dataset_inhom_model_data(SEXP ptrSEXP, SEXP image_areaSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP edge_correctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type image_area(image_areaSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    Rcpp::traits::input_parameter< bool >::type edge_correct(edge_correctSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_inhom_model_data(ptr, image_area, from, to, edge_correct));
    return rcpp_result_gen;
END_RCPP
}
// dataset_build_context
void dataset_build_context(SEXP ptr, IntegerVector context_types, std::string window, bool edge_correct);
RcppExport SEXP _spicyR_dataset_build_context(SEXP ptrSEXP, SEXP context_typesSEXP, SEXP windowSEXP, SEXP edge_correctSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type context_types(context_typesSEXP);
    Rcpp::traits::input_parameter< std::string >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type edge_correct(edge_correctSEXP);
    dataset_build_context(ptr, context_types, window, edge_correct);
    return R_NilValue;
END_RCPP
}
// dataset_kontextual_model_data
List dataset_kontextual_model_data(SEXP ptr, int from, int to);
RcppExport SEXP _spicyR_dataset_kontextual_model_data(SEXP ptrSEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_kontextual_model_data(ptr, from, to));
    return rcpp_result_gen;
END_RCPP
}
// dataset_kontextual_binomial_model_data
List dataset_kontextual_binomial_model_data(SEXP ptr, int from, int to);
RcppExport SEXP _spicyR_dataset_kontextual_binomial_model_data(SEXP ptrSEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_kontextual_binomial_model_data(ptr, from, to));
    return rcpp_result_gen;
END_RCPP
}
// dataset_binomial_model_data
List dataset_binomial_model_data(SEXP ptr, int from, int to);
RcppExport SEXP _spicyR_dataset_binomial_model_data(SEXP ptrSEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_binomial_model_data(ptr, from, to));
    return rcpp_result_gen;
END_RCPP
}
// fit_pair_poisson_cpp
List fit_pair_poisson_cpp(IntegerVector cluster, IntegerVector image, IntegerVector group, NumericVector n, NumericVector density, std::string estimator, std::string variance, bool diagnostics);
RcppExport SEXP _spicyR_fit_pair_poisson_cpp(SEXP clusterSEXP, SEXP imageSEXP, SEXP groupSEXP, SEXP nSEXP, SEXP densitySEXP, SEXP estimatorSEXP, SEXP varianceSEXP, SEXP diagnosticsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type cluster(clusterSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type image(imageSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type density(densitySEXP);
    Rcpp::traits::input_parameter< std::string >::type estimator(estimatorSEXP);
    Rcpp::traits::input_parameter< std::string >::type variance(varianceSEXP);
    Rcpp::traits::input_parameter< bool >::type diagnostics(diagnosticsSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_pair_poisson_cpp(cluster, image, group, n, density, estimator, variance, diagnostics));
    return rcpp_result_gen;
END_RCPP
}
// fit_pair_binomial_cpp
List fit_pair_binomial_cpp(IntegerVector cluster, IntegerVector image, IntegerVector group, IntegerVector n, int k, NumericVector p0, std::string estimator, std::string variance);
RcppExport SEXP _spicyR_fit_pair_binomial_cpp(SEXP clusterSEXP, SEXP imageSEXP, SEXP groupSEXP, SEXP nSEXP, SEXP kSEXP, SEXP p0SEXP, SEXP estimatorSEXP, SEXP varianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type cluster(clusterSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type image(imageSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< std::string >::type estimator(estimatorSEXP);
    Rcpp::traits::input_parameter< std::string >::type variance(varianceSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_pair_binomial_cpp(cluster, image, group, n, k, p0, estimator, variance));
    return rcpp_result_gen;
END_RCPP
}
// fit_pair_binomial_trials_cpp
List fit_pair_binomial_trials_cpp(IntegerVector cluster, IntegerVector image, IntegerVector group, IntegerVector n, IntegerVector trials, NumericVector p0, std::string estimator, std::string variance);
RcppExport SEXP _spicyR_fit_pair_binomial_trials_cpp(SEXP clusterSEXP, SEXP imageSEXP, SEXP groupSEXP, SEXP nSEXP, SEXP trialsSEXP, SEXP p0SEXP, SEXP estimatorSEXP, SEXP varianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type cluster(clusterSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type image(imageSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type trials(trialsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< std::string >::type estimator(estimatorSEXP);
    Rcpp::traits::input_parameter< std::string >::type variance(varianceSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_pair_binomial_trials_cpp(cluster, image, group, n, trials, p0, estimator, variance));
    return rcpp_result_gen;
END_RCPP
}
// dataset_pair_neighbour_totals
NumericVector dataset_pair_neighbour_totals(SEXP ptr, bool knn, int n_types);
RcppExport SEXP _spicyR_dataset_pair_neighbour_totals(SEXP ptrSEXP, SEXP knnSEXP, SEXP n_typesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< bool >::type knn(knnSEXP);
    Rcpp::traits::input_parameter< int >::type n_types(n_typesSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_pair_neighbour_totals(ptr, knn, n_types));
    return rcpp_result_gen;
END_RCPP
}
// dataset_pair_neighbour_sq_totals
NumericVector dataset_pair_neighbour_sq_totals(SEXP ptr, bool knn, int n_types);
RcppExport SEXP _spicyR_dataset_pair_neighbour_sq_totals(SEXP ptrSEXP, SEXP knnSEXP, SEXP n_typesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< bool >::type knn(knnSEXP);
    Rcpp::traits::input_parameter< int >::type n_types(n_typesSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_pair_neighbour_sq_totals(ptr, knn, n_types));
    return rcpp_result_gen;
END_RCPP
}
// dataset_pair_neighbour_out_sq_totals
NumericVector dataset_pair_neighbour_out_sq_totals(SEXP ptr, bool knn, int n_types);
RcppExport SEXP _spicyR_dataset_pair_neighbour_out_sq_totals(SEXP ptrSEXP, SEXP knnSEXP, SEXP n_typesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< bool >::type knn(knnSEXP);
    Rcpp::traits::input_parameter< int >::type n_types(n_typesSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_pair_neighbour_out_sq_totals(ptr, knn, n_types));
    return rcpp_result_gen;
END_RCPP
}
// dataset_rl_model_data
List dataset_rl_model_data(SEXP ptr, int from, int to);
RcppExport SEXP _spicyR_dataset_rl_model_data(SEXP ptrSEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_rl_model_data(ptr, from, to));
    return rcpp_result_gen;
END_RCPP
}
// dataset_weighted_phi_sums
NumericMatrix dataset_weighted_phi_sums(SEXP ptr, int from, int to, int design, bool edge_correct);
RcppExport SEXP _spicyR_dataset_weighted_phi_sums(SEXP ptrSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP designSEXP, SEXP edge_correctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    Rcpp::traits::input_parameter< int >::type design(designSEXP);
    Rcpp::traits::input_parameter< bool >::type edge_correct(edge_correctSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_weighted_phi_sums(ptr, from, to, design, edge_correct));
    return rcpp_result_gen;
END_RCPP
}
// dataset_kontextual_sums
NumericMatrix dataset_kontextual_sums(SEXP ptr, int from, int to);
RcppExport SEXP _spicyR_dataset_kontextual_sums(SEXP ptrSEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_kontextual_sums(ptr, from, to));
    return rcpp_result_gen;
END_RCPP
}
// dataset_hac_phi_sums_ref
NumericMatrix dataset_hac_phi_sums_ref(SEXP ptr, int from, int design, double h, int n_types);
RcppExport SEXP _spicyR_dataset_hac_phi_sums_ref(SEXP ptrSEXP, SEXP fromSEXP, SEXP designSEXP, SEXP hSEXP, SEXP n_typesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type design(designSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type n_types(n_typesSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_hac_phi_sums_ref(ptr, from, design, h, n_types));
    return rcpp_result_gen;
END_RCPP
}
// dataset_hac_phi_sums
NumericMatrix dataset_hac_phi_sums(SEXP ptr, int from, int to, int design, double h);
RcppExport SEXP _spicyR_dataset_hac_phi_sums(SEXP ptrSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP designSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    Rcpp::traits::input_parameter< int >::type design(designSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(dataset_hac_phi_sums(ptr, from, to, design, h));
    return rcpp_result_gen;
END_RCPP
}
// inhomLCpp
Rcpp::NumericMatrix inhomLCpp(Rcpp::NumericVector x, Rcpp::NumericVector y, Rcpp::IntegerVector type, int nTypes, Rcpp::NumericVector Rs, Rcpp::NumericVector labelVal, Rcpp::LogicalVector isFrom, Rcpp::LogicalVector isTo, Rcpp::NumericVector wt, Rcpp::NumericVector lam, double area, Rcpp::NumericMatrix edge, bool edgeCorrect);
RcppExport SEXP _spicyR_inhomLCpp(SEXP xSEXP, SEXP ySEXP, SEXP typeSEXP, SEXP nTypesSEXP, SEXP RsSEXP, SEXP labelValSEXP, SEXP isFromSEXP, SEXP isToSEXP, SEXP wtSEXP, SEXP lamSEXP, SEXP areaSEXP, SEXP edgeSEXP, SEXP edgeCorrectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type nTypes(nTypesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type labelVal(labelValSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type isFrom(isFromSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type isTo(isToSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type area(areaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< bool >::type edgeCorrect(edgeCorrectSEXP);
    rcpp_result_gen = Rcpp::wrap(inhomLCpp(x, y, type, nTypes, Rs, labelVal, isFrom, isTo, wt, lam, area, edge, edgeCorrect));
    return rcpp_result_gen;
END_RCPP
}
// lmerRandomIntercept
Rcpp::List lmerRandomIntercept(Rcpp::NumericMatrix X, Rcpp::NumericVector y, Rcpp::NumericVector w, Rcpp::IntegerVector group, int G);
RcppExport SEXP _spicyR_lmerRandomIntercept(SEXP XSEXP, SEXP ySEXP, SEXP wSEXP, SEXP groupSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(lmerRandomIntercept(X, y, w, group, G));
    return rcpp_result_gen;
END_RCPP
}
// getPairwiseCpp
Rcpp::NumericMatrix getPairwiseCpp(Rcpp::NumericVector x, Rcpp::NumericVector y, Rcpp::IntegerVector type, Rcpp::IntegerVector offset, int nTypes, Rcpp::NumericVector Rs, bool square, Rcpp::LogicalVector isFrom, Rcpp::LogicalVector isTo, Rcpp::IntegerVector labI, Rcpp::IntegerVector labJ, bool edgeCorrect, bool includeZeroCells, int nThreads);
RcppExport SEXP _spicyR_getPairwiseCpp(SEXP xSEXP, SEXP ySEXP, SEXP typeSEXP, SEXP offsetSEXP, SEXP nTypesSEXP, SEXP RsSEXP, SEXP squareSEXP, SEXP isFromSEXP, SEXP isToSEXP, SEXP labISEXP, SEXP labJSEXP, SEXP edgeCorrectSEXP, SEXP includeZeroCellsSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type nTypes(nTypesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Rs(RsSEXP);
    Rcpp::traits::input_parameter< bool >::type square(squareSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type isFrom(isFromSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type isTo(isToSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type labI(labISEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type labJ(labJSEXP);
    Rcpp::traits::input_parameter< bool >::type edgeCorrect(edgeCorrectSEXP);
    Rcpp::traits::input_parameter< bool >::type includeZeroCells(includeZeroCellsSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(getPairwiseCpp(x, y, type, offset, nTypes, Rs, square, isFrom, isTo, labI, labJ, edgeCorrect, includeZeroCells, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// getPairwisePropCpp
Rcpp::NumericMatrix getPairwisePropCpp(Rcpp::NumericVector x, Rcpp::NumericVector y, Rcpp::IntegerVector type, Rcpp::IntegerVector offset, int nTypes, int k, Rcpp::IntegerVector labI, Rcpp::IntegerVector labJ, bool includeZeroCells, int nThreads);
RcppExport SEXP _spicyR_getPairwisePropCpp(SEXP xSEXP, SEXP ySEXP, SEXP typeSEXP, SEXP offsetSEXP, SEXP nTypesSEXP, SEXP kSEXP, SEXP labISEXP, SEXP labJSEXP, SEXP includeZeroCellsSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type nTypes(nTypesSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type labI(labISEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type labJ(labJSEXP);
    Rcpp::traits::input_parameter< bool >::type includeZeroCells(includeZeroCellsSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(getPairwisePropCpp(x, y, type, offset, nTypes, k, labI, labJ, includeZeroCells, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// scamMonoFit
Rcpp::List scamMonoFit(Rcpp::NumericMatrix XtX, Rcpp::NumericVector Xty, double yty, int n, Rcpp::List S, Rcpp::LogicalVector iv, Rcpp::NumericVector start, Rcpp::IntegerVector blockStart, Rcpp::IntegerVector blockLen);
RcppExport SEXP _spicyR_scamMonoFit(SEXP XtXSEXP, SEXP XtySEXP, SEXP ytySEXP, SEXP nSEXP, SEXP SSEXP, SEXP ivSEXP, SEXP startSEXP, SEXP blockStartSEXP, SEXP blockLenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type XtX(XtXSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Xty(XtySEXP);
    Rcpp::traits::input_parameter< double >::type yty(ytySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type S(SSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type iv(ivSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type blockStart(blockStartSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type blockLen(blockLenSEXP);
    rcpp_result_gen = Rcpp::wrap(scamMonoFit(XtX, Xty, yty, n, S, iv, start, blockStart, blockLen));
    return rcpp_result_gen;
END_RCPP
}
// stats_pt_two_sided
NumericVector stats_pt_two_sided(NumericVector t, double df);
RcppExport SEXP _spicyR_stats_pt_two_sided(SEXP tSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(stats_pt_two_sided(t, df));
    return rcpp_result_gen;
END_RCPP
}
// stats_norm_quantile
NumericVector stats_norm_quantile(NumericVector p);
RcppExport SEXP _spicyR_stats_norm_quantile(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(stats_norm_quantile(p));
    return rcpp_result_gen;
END_RCPP
}
// stats_excess_image_rows
DataFrame stats_excess_image_rows(NumericVector totals, NumericVector out_sq_totals, NumericMatrix counts, int from, int to, bool knn, NumericMatrix psi);
RcppExport SEXP _spicyR_stats_excess_image_rows(SEXP totalsSEXP, SEXP out_sq_totalsSEXP, SEXP countsSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP knnSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type totals(totalsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type out_sq_totals(out_sq_totalsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    Rcpp::traits::input_parameter< bool >::type knn(knnSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(stats_excess_image_rows(totals, out_sq_totals, counts, from, to, knn, psi));
    return rcpp_result_gen;
END_RCPP
}
// stats_kontextual_image_rows
DataFrame stats_kontextual_image_rows(NumericMatrix sums, NumericMatrix counts, int from, int to, NumericMatrix psi);
RcppExport SEXP _spicyR_stats_kontextual_image_rows(SEXP sumsSEXP, SEXP countsSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type sums(sumsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(stats_kontextual_image_rows(sums, counts, from, to, psi));
    return rcpp_result_gen;
END_RCPP
}
// stats_kontextual_clustering
NumericMatrix stats_kontextual_clustering(SEXP ptr, IntegerVector from, IntegerVector to, NumericMatrix raw, NumericMatrix counts, double h);
RcppExport SEXP _spicyR_stats_kontextual_clustering(SEXP ptrSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP rawSEXP, SEXP countsSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type raw(rawSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(stats_kontextual_clustering(ptr, from, to, raw, counts, h));
    return rcpp_result_gen;
END_RCPP
}
// stats_label_clustering
NumericMatrix stats_label_clustering(SEXP ptr, IntegerVector from, IntegerVector to, NumericMatrix counts, bool knn, double h);
RcppExport SEXP _spicyR_stats_label_clustering(SEXP ptrSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP countsSEXP, SEXP knnSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< bool >::type knn(knnSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(stats_label_clustering(ptr, from, to, counts, knn, h));
    return rcpp_result_gen;
END_RCPP
}
// stats_excess_test
List stats_excess_test(DataFrame rows, IntegerVector unit, IntegerVector group, int n_units, bool frailty, std::string variance);
RcppExport SEXP _spicyR_stats_excess_test(SEXP rowsSEXP, SEXP unitSEXP, SEXP groupSEXP, SEXP n_unitsSEXP, SEXP frailtySEXP, SEXP varianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type unit(unitSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< bool >::type frailty(frailtySEXP);
    Rcpp::traits::input_parameter< std::string >::type variance(varianceSEXP);
    rcpp_result_gen = Rcpp::wrap(stats_excess_test(rows, unit, group, n_units, frailty, variance));
    return rcpp_result_gen;
END_RCPP
}
// stats_design_test
List stats_design_test(DataFrame rows, IntegerVector unit, int n_units, NumericMatrix Z, NumericVector contrast, double tau2);
RcppExport SEXP _spicyR_stats_design_test(SEXP rowsSEXP, SEXP unitSEXP, SEXP n_unitsSEXP, SEXP ZSEXP, SEXP contrastSEXP, SEXP tau2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type unit(unitSEXP);
    Rcpp::traits::input_parameter< int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type contrast(contrastSEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    rcpp_result_gen = Rcpp::wrap(stats_design_test(rows, unit, n_units, Z, contrast, tau2));
    return rcpp_result_gen;
END_RCPP
}
// stats_design_tests
List stats_design_tests(DataFrame rows, IntegerVector unit, int n_units, NumericMatrix Z, NumericMatrix contrasts, double tau2, bool hartung_knapp);
RcppExport SEXP _spicyR_stats_design_tests(SEXP rowsSEXP, SEXP unitSEXP, SEXP n_unitsSEXP, SEXP ZSEXP, SEXP contrastsSEXP, SEXP tau2SEXP, SEXP hartung_knappSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type unit(unitSEXP);
    Rcpp::traits::input_parameter< int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type contrasts(contrastsSEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< bool >::type hartung_knapp(hartung_knappSEXP);
    rcpp_result_gen = Rcpp::wrap(stats_design_tests(rows, unit, n_units, Z, contrasts, tau2, hartung_knapp));
    return rcpp_result_gen;
END_RCPP
}
// stats_availability_test
List stats_availability_test(DataFrame rows, IntegerVector unit, IntegerVector group, int n_units, NumericVector x, double tau2);
RcppExport SEXP _spicyR_stats_availability_test(SEXP rowsSEXP, SEXP unitSEXP, SEXP groupSEXP, SEXP n_unitsSEXP, SEXP xSEXP, SEXP tau2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type unit(unitSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    rcpp_result_gen = Rcpp::wrap(stats_availability_test(rows, unit, group, n_units, x, tau2));
    return rcpp_result_gen;
END_RCPP
}
// stats_cox_fit
List stats_cox_fit(NumericVector time, IntegerVector event, NumericMatrix X);
RcppExport SEXP _spicyR_stats_cox_fit(SEXP timeSEXP, SEXP eventSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type event(eventSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(stats_cox_fit(time, event, X));
    return rcpp_result_gen;
END_RCPP
}
// stats_survival_test
List stats_survival_test(DataFrame rows, IntegerVector unit, int n_units, NumericVector martingale, NumericVector time, IntegerVector event, NumericVector x);
RcppExport SEXP _spicyR_stats_survival_test(SEXP rowsSEXP, SEXP unitSEXP, SEXP n_unitsSEXP, SEXP martingaleSEXP, SEXP timeSEXP, SEXP eventSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type unit(unitSEXP);
    Rcpp::traits::input_parameter< int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type martingale(martingaleSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type event(eventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(stats_survival_test(rows, unit, n_units, martingale, time, event, x));
    return rcpp_result_gen;
END_RCPP
}
// stats_cauchy
double stats_cauchy(NumericVector p);
RcppExport SEXP _spicyR_stats_cauchy(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(stats_cauchy(p));
    return rcpp_result_gen;
END_RCPP
}
// stats_max_t
List stats_max_t(NumericMatrix influence, NumericVector t, NumericVector df);
RcppExport SEXP _spicyR_stats_max_t(SEXP influenceSEXP, SEXP tSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type influence(influenceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(stats_max_t(influence, t, df));
    return rcpp_result_gen;
END_RCPP
}
// stats_mvn_outside
double stats_mvn_outside(NumericVector lower, NumericVector upper, NumericMatrix R);
RcppExport SEXP _spicyR_stats_mvn_outside(SEXP lowerSEXP, SEXP upperSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(stats_mvn_outside(lower, upper, R));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spicyR_discWindowArea", (DL_FUNC) &_spicyR_discWindowArea, 5},
    {"_spicyR_dataset_create", (DL_FUNC) &_spicyR_dataset_create, 5},
    {"_spicyR_dataset_image_areas", (DL_FUNC) &_spicyR_dataset_image_areas, 2},
    {"_spicyR_dataset_build_radius_index", (DL_FUNC) &_spicyR_dataset_build_radius_index, 2},
    {"_spicyR_dataset_build_knn", (DL_FUNC) &_spicyR_dataset_build_knn, 3},
    {"_spicyR_dataset_poisson_model_data", (DL_FUNC) &_spicyR_dataset_poisson_model_data, 4},
    {"_spicyR_dataset_build_intensity", (DL_FUNC) &_spicyR_dataset_build_intensity, 4},
    {"_spicyR_dataset_inhom_model_data", (DL_FUNC) &_spicyR_dataset_inhom_model_data, 5},
    {"_spicyR_dataset_build_context", (DL_FUNC) &_spicyR_dataset_build_context, 4},
    {"_spicyR_dataset_kontextual_model_data", (DL_FUNC) &_spicyR_dataset_kontextual_model_data, 3},
    {"_spicyR_dataset_kontextual_binomial_model_data", (DL_FUNC) &_spicyR_dataset_kontextual_binomial_model_data, 3},
    {"_spicyR_dataset_binomial_model_data", (DL_FUNC) &_spicyR_dataset_binomial_model_data, 3},
    {"_spicyR_fit_pair_poisson_cpp", (DL_FUNC) &_spicyR_fit_pair_poisson_cpp, 8},
    {"_spicyR_fit_pair_binomial_cpp", (DL_FUNC) &_spicyR_fit_pair_binomial_cpp, 8},
    {"_spicyR_fit_pair_binomial_trials_cpp", (DL_FUNC) &_spicyR_fit_pair_binomial_trials_cpp, 8},
    {"_spicyR_dataset_pair_neighbour_totals", (DL_FUNC) &_spicyR_dataset_pair_neighbour_totals, 3},
    {"_spicyR_dataset_pair_neighbour_sq_totals", (DL_FUNC) &_spicyR_dataset_pair_neighbour_sq_totals, 3},
    {"_spicyR_dataset_pair_neighbour_out_sq_totals", (DL_FUNC) &_spicyR_dataset_pair_neighbour_out_sq_totals, 3},
    {"_spicyR_dataset_rl_model_data", (DL_FUNC) &_spicyR_dataset_rl_model_data, 3},
    {"_spicyR_dataset_weighted_phi_sums", (DL_FUNC) &_spicyR_dataset_weighted_phi_sums, 5},
    {"_spicyR_dataset_kontextual_sums", (DL_FUNC) &_spicyR_dataset_kontextual_sums, 3},
    {"_spicyR_dataset_hac_phi_sums_ref", (DL_FUNC) &_spicyR_dataset_hac_phi_sums_ref, 5},
    {"_spicyR_dataset_hac_phi_sums", (DL_FUNC) &_spicyR_dataset_hac_phi_sums, 5},
    {"_spicyR_inhomLCpp", (DL_FUNC) &_spicyR_inhomLCpp, 13},
    {"_spicyR_lmerRandomIntercept", (DL_FUNC) &_spicyR_lmerRandomIntercept, 5},
    {"_spicyR_getPairwiseCpp", (DL_FUNC) &_spicyR_getPairwiseCpp, 14},
    {"_spicyR_getPairwisePropCpp", (DL_FUNC) &_spicyR_getPairwisePropCpp, 10},
    {"_spicyR_scamMonoFit", (DL_FUNC) &_spicyR_scamMonoFit, 9},
    {"_spicyR_stats_pt_two_sided", (DL_FUNC) &_spicyR_stats_pt_two_sided, 2},
    {"_spicyR_stats_norm_quantile", (DL_FUNC) &_spicyR_stats_norm_quantile, 1},
    {"_spicyR_stats_excess_image_rows", (DL_FUNC) &_spicyR_stats_excess_image_rows, 7},
    {"_spicyR_stats_kontextual_image_rows", (DL_FUNC) &_spicyR_stats_kontextual_image_rows, 5},
    {"_spicyR_stats_kontextual_clustering", (DL_FUNC) &_spicyR_stats_kontextual_clustering, 6},
    {"_spicyR_stats_label_clustering", (DL_FUNC) &_spicyR_stats_label_clustering, 6},
    {"_spicyR_stats_excess_test", (DL_FUNC) &_spicyR_stats_excess_test, 6},
    {"_spicyR_stats_design_test", (DL_FUNC) &_spicyR_stats_design_test, 6},
    {"_spicyR_stats_design_tests", (DL_FUNC) &_spicyR_stats_design_tests, 7},
    {"_spicyR_stats_availability_test", (DL_FUNC) &_spicyR_stats_availability_test, 6},
    {"_spicyR_stats_cox_fit", (DL_FUNC) &_spicyR_stats_cox_fit, 3},
    {"_spicyR_stats_survival_test", (DL_FUNC) &_spicyR_stats_survival_test, 7},
    {"_spicyR_stats_cauchy", (DL_FUNC) &_spicyR_stats_cauchy, 1},
    {"_spicyR_stats_max_t", (DL_FUNC) &_spicyR_stats_max_t, 3},
    {"_spicyR_stats_mvn_outside", (DL_FUNC) &_spicyR_stats_mvn_outside, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_spicyR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
