# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

discWindowArea <- function(x, y, r, npoly, rings) {
    .Call(`_spicyR_discWindowArea`, x, y, r, npoly, rings)
}

dataset_create <- function(x, y, cell_type, image_offsets, n_types) {
    .Call(`_spicyR_dataset_create`, x, y, cell_type, image_offsets, n_types)
}

dataset_image_areas <- function(ptr, window) {
    .Call(`_spicyR_dataset_image_areas`, ptr, window)
}

dataset_build_radius_index <- function(ptr, r) {
    invisible(.Call(`_spicyR_dataset_build_radius_index`, ptr, r))
}

dataset_build_knn <- function(ptr, k, n_threads = 1L) {
    invisible(.Call(`_spicyR_dataset_build_knn`, ptr, k, n_threads))
}

dataset_poisson_model_data <- function(ptr, image_area, from, to) {
    .Call(`_spicyR_dataset_poisson_model_data`, ptr, image_area, from, to)
}

dataset_build_intensity <- function(ptr, sigma, min_lambda, window) {
    invisible(.Call(`_spicyR_dataset_build_intensity`, ptr, sigma, min_lambda, window))
}

dataset_inhom_model_data <- function(ptr, image_area, from, to, edge_correct) {
    .Call(`_spicyR_dataset_inhom_model_data`, ptr, image_area, from, to, edge_correct)
}

dataset_build_context <- function(ptr, context_types, window, edge_correct) {
    invisible(.Call(`_spicyR_dataset_build_context`, ptr, context_types, window, edge_correct))
}

dataset_kontextual_model_data <- function(ptr, from, to) {
    .Call(`_spicyR_dataset_kontextual_model_data`, ptr, from, to)
}

dataset_kontextual_binomial_model_data <- function(ptr, from, to) {
    .Call(`_spicyR_dataset_kontextual_binomial_model_data`, ptr, from, to)
}

dataset_binomial_model_data <- function(ptr, from, to) {
    .Call(`_spicyR_dataset_binomial_model_data`, ptr, from, to)
}

fit_pair_poisson_cpp <- function(cluster, image, group, n, density, estimator, variance, diagnostics = FALSE) {
    .Call(`_spicyR_fit_pair_poisson_cpp`, cluster, image, group, n, density, estimator, variance, diagnostics)
}

fit_pair_binomial_cpp <- function(cluster, image, group, n, k, p0, estimator, variance) {
    .Call(`_spicyR_fit_pair_binomial_cpp`, cluster, image, group, n, k, p0, estimator, variance)
}

fit_pair_binomial_trials_cpp <- function(cluster, image, group, n, trials, p0, estimator, variance) {
    .Call(`_spicyR_fit_pair_binomial_trials_cpp`, cluster, image, group, n, trials, p0, estimator, variance)
}

dataset_pair_neighbour_totals <- function(ptr, knn, n_types) {
    .Call(`_spicyR_dataset_pair_neighbour_totals`, ptr, knn, n_types)
}

dataset_pair_neighbour_sq_totals <- function(ptr, knn, n_types) {
    .Call(`_spicyR_dataset_pair_neighbour_sq_totals`, ptr, knn, n_types)
}

dataset_pair_neighbour_out_sq_totals <- function(ptr, knn, n_types) {
    .Call(`_spicyR_dataset_pair_neighbour_out_sq_totals`, ptr, knn, n_types)
}

dataset_rl_model_data <- function(ptr, from, to) {
    .Call(`_spicyR_dataset_rl_model_data`, ptr, from, to)
}

dataset_weighted_phi_sums <- function(ptr, from, to, design, edge_correct) {
    .Call(`_spicyR_dataset_weighted_phi_sums`, ptr, from, to, design, edge_correct)
}

dataset_hac_phi_sums_ref <- function(ptr, from, design, h, n_types) {
    .Call(`_spicyR_dataset_hac_phi_sums_ref`, ptr, from, design, h, n_types)
}

dataset_hac_phi_sums <- function(ptr, from, to, design, h) {
    .Call(`_spicyR_dataset_hac_phi_sums`, ptr, from, to, design, h)
}

inhomLCpp <- function(x, y, type, nTypes, Rs, labelVal, isFrom, isTo, wt, lam, area, edge, edgeCorrect) {
    .Call(`_spicyR_inhomLCpp`, x, y, type, nTypes, Rs, labelVal, isFrom, isTo, wt, lam, area, edge, edgeCorrect)
}

lmerRandomIntercept <- function(X, y, w, group, G) {
    .Call(`_spicyR_lmerRandomIntercept`, X, y, w, group, G)
}

getPairwiseCpp <- function(x, y, type, offset, nTypes, Rs, square, isFrom, isTo, labI, labJ, edgeCorrect, includeZeroCells, nThreads) {
    .Call(`_spicyR_getPairwiseCpp`, x, y, type, offset, nTypes, Rs, square, isFrom, isTo, labI, labJ, edgeCorrect, includeZeroCells, nThreads)
}

getPairwisePropCpp <- function(x, y, type, offset, nTypes, k, labI, labJ, includeZeroCells, nThreads) {
    .Call(`_spicyR_getPairwisePropCpp`, x, y, type, offset, nTypes, k, labI, labJ, includeZeroCells, nThreads)
}

scamMonoFit <- function(XtX, Xty, yty, n, S, iv, start, blockStart, blockLen) {
    .Call(`_spicyR_scamMonoFit`, XtX, Xty, yty, n, S, iv, start, blockStart, blockLen)
}

