# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

discWindowArea <- function(x, y, r, npoly, rings) {
    .Call(`_spicyR_discWindowArea`, x, y, r, npoly, rings)
}

inhomLCpp <- function(x, y, type, nTypes, Rs, labelVal, isFrom, isTo, wt, lam, area, edge, edgeCorrect) {
    .Call(`_spicyR_inhomLCpp`, x, y, type, nTypes, Rs, labelVal, isFrom, isTo, wt, lam, area, edge, edgeCorrect)
}

lmerRandomIntercept <- function(X, y, w, group, G) {
    .Call(`_spicyR_lmerRandomIntercept`, X, y, w, group, G)
}

getPairwiseCpp <- function(x, y, type, offset, nTypes, Rs, square, isFrom, isTo, labI, labJ, edgeCorrect, includeZeroCells, nThreads) {
    .Call(`_spicyR_getPairwiseCpp`, x, y, type, offset, nTypes, Rs, square, isFrom, isTo, labI, labJ, edgeCorrect, includeZeroCells, nThreads)
}

scamMonoFit <- function(XtX, Xty, yty, n, S, iv, start, blockStart, blockLen) {
    .Call(`_spicyR_scamMonoFit`, XtX, Xty, yty, n, S, iv, start, blockStart, blockLen)
}

